### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by kerim** [xmollv/Llitgi#22]
Would be nice to have a white-on-Black theme.

**Comment by xmollv** [comment]
Hey there! Yes, this is something that I've been thinking about doing, but I still need to look for a decent solution. Let's hope that this weekend I have some free time to spend doing this!

**Comment by xmollv** [comment]
I've been reading about implementing themes, and I don't want to do it with `UIAppearance` because to change the theme at runtime, you have to remove all your views from your `UIWindow` and put them back 🤮

I found this blogpost: https://medium.com/@bradgmueller/follow-me-to-the-dark-side-65e24151a29c that seems like a nice idea. I'll try to do that as soon as I finish with the implementation of Coordinators.

**Comment by FWDavide** [comment]
Mandatory having dark mode for readability.

**Comment by FWDavide** [comment]
Congratulations for the implementation of this mandatory and vital feature
