### ISSUE TITLE
Enable logging in with a different user

### ISSUE THREAD

**Issue by atineoSE** [xmollv/Llitgi#34]
As it is right now, once the user logs in once, then she will be logged in immediately next time. This makes it impractical to use the app with different Pocket accounts (only way to enter a new user is by uninstalling the app). 

This is particularly meaningful in the case of iPad, where devices are typically shared among family members.

**Comment by xmollv** [comment]
How are you loggin into the app? By using the Pocket app or the website? If it's the website, AFAIK you should logout from the website, otherwise it redirects you automatically and does the login. But, I'm thinking that for the login we use `SFSafariViewController`, and if I'm not mistaken, since iOS 11 it doesn't share the storage with Safari. From the top of my mind right now I don't know how to erase the previous session on the Pocket website from the SFS so it doesn't automatically log you in, if you have any idea please do let me know!

**Comment by atineoSE** [comment]
@xmollv yes, I login via web, and yes, it redirects automatically and logs me in right away after logging out. I was not aware of the login via Pocket app.

I'll have a look and propose something.

**Comment by xmollv** [comment]
@atineoSE yeah, the first attempt is to log in by using the Pocket app if you have it installed it, because  it's usually faster and more _magical_. Let me know about what you find for the web login to see if it's something that I'd like to have available or not. I think that this case is a pretty edge case, so if it's something simple go for it, if it starts becoming something complex, I'd like to avoid it. Anyway, let me know about anything that you find 🙌

**Comment by atineoSE** [comment]
@xmollv I had a quick look at the issue and here is what I found.

Since iOS 11 `SFSafariViewController` does not share cookies anymore with Safari. Additionally, `SFSafariViewController` does not expose cookies to the app so there is no chance to access them directly or clear them from the app. Class `SFAuthenticationSession` allows to share a one-time login between the app and Safari, but only the auth token is returned, it doesn't look like we can reset the session then, or at least I can't see an obvious way to do it. 

Most information out there is anyways for iOS 9 or 10, when cookies where shared, so all that info is obsolete now. 

Following your comment of not increasing complexity for an edge case, I guess we can drop this issue.

**Comment by xmollv** [comment]
If you find a solution -even if it's not simple- let me know and we can talk about it!. I'm closing this issue for now.
