### ISSUE TITLE
White screen in dark mode

### ISSUE THREAD

**Issue by kerim** [xmollv/Llitgi#41]
When opening a page in Dark Mode, even when a dark theme is set in the Safari reader, the screen flashes white before the page loads. Is this something that only Apple can fix, or could the app perhaps be updated to load a black screen while loading? (When reading at night the flash of white is very disturbing...)

**Comment by xmollv** [comment]
@kerim I can make the view's `backgroundColor` to be the same as the theme, but I've been testing it and it makes things even worse because the flash is more noticeable. I don't know who is applying the white background, it could be the default implementation while loading the webpage or just because 99.9% of the websites have the background as white. I'll close this for now.
